"""first revision

Revision ID: 0ff971fe135a
Revises: 
Create Date: 2023-01-26 10:57:00.271765

"""
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0ff971fe135a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("markes")
    op.drop_table("vidhyarthi")
    op.add_column("student", sa.Column("surname", sa.String(length=200), nullable=True))
    op.add_column("student", sa.Column("name", sa.String(length=200), nullable=True))
    op.add_column(
        "student",
        sa.Column(
            "field",
            sa.Enum("science", "commarce", "arts", name="fieldnameenum"),
            nullable=True,
        ),
    )
    op.add_column(
        "student",
        sa.Column("std", sa.Enum("eleven", "twelve", name="stdenum"), nullable=True),
    )
    op.add_column(
        "student",
        sa.Column(
            "div",
            sa.Enum("eleven_a", "eleven_b", "twelve_a", "twelve_b", name="divenv"),
            nullable=True,
        ),
    )
    op.add_column("student", sa.Column("city", sa.String(length=200), nullable=True))
    op.drop_column("student", "st_city")
    op.drop_column("student", "st_div")
    op.drop_column("student", "st_std")
    op.drop_column("student", "st_name")
    op.drop_column("student", "st_surname")
    op.drop_column("student", "st_field")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column("st_field", mysql.ENUM("science", "commarce", "arts"), nullable=True),
    )
    op.add_column(
        "student", sa.Column("st_surname", mysql.VARCHAR(length=200), nullable=False)
    )
    op.add_column(
        "student", sa.Column("st_name", mysql.VARCHAR(length=200), nullable=True)
    )
    op.add_column(
        "student", sa.Column("st_std", mysql.ENUM("eleven", "twelve"), nullable=True)
    )
    op.add_column(
        "student",
        sa.Column(
            "st_div",
            mysql.ENUM("eleven_a", "eleven_b", "twelve_a", "twelve_b"),
            nullable=True,
        ),
    )
    op.add_column(
        "student", sa.Column("st_city", mysql.VARCHAR(length=200), nullable=True)
    )
    op.drop_column("student", "city")
    op.drop_column("student", "div")
    op.drop_column("student", "std")
    op.drop_column("student", "field")
    op.drop_column("student", "name")
    op.drop_column("student", "surname")
    op.create_table(
        "vidhyarthi",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "markes",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "vidhyarthi_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("subject_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("marks", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
