"""second revision

Revision ID: 6e1d83777537
Revises: 0ff971fe135a
Create Date: 2023-01-26 11:00:10.203689

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6e1d83777537"
down_revision = "0ff971fe135a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student",
        sa.Column("id", sa.String(length=200), nullable=False),
        sa.Column("surname", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "field",
            sa.Enum("science", "commarce", "arts", name="fieldnameenum"),
            nullable=True,
        ),
        sa.Column("std", sa.Enum("eleven", "twelve", name="stdenum"), nullable=True),
        sa.Column(
            "div",
            sa.Enum("eleven_a", "eleven_b", "twelve_a", "twelve_b", name="divenv"),
            nullable=True,
        ),
        sa.Column("city", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student")
    # ### end Alembic commands ###
