"""create user table

Revision ID: e041b3b360b5
Revises: 6e1d83777537
Create Date: 2023-01-26 12:45:17.117735

"""
import sqlalchemy as sa

from alembic import op
from database import sesssionLocal
from libs.utils import _create_password, generate_id
from models import UserModel

# revision identifiers, used by Alembic.
revision = "e041b3b360b5"
down_revision = "6e1d83777537"
branch_labels = None
depends_on = None


def add_user():
    _id = generate_id()
    db = sesssionLocal()
    db_user = UserModel(
        id=_id, email="ronak@gmail.com", password=_create_password(password="123456")
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    db.close()
    return


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=60), nullable=True),
        sa.Column("password", sa.String(length=60), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###

    add_user()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
